apiVersion: v1
kind: ConfigMap
metadata:
  name: komodor-python-script
data:
  python-script: |-
    import time
    import os
    import sys
    import logging
    logging.basicConfig(stream=sys.stdout, level=logging.INFO)

    def start_service():
        initialize_connections()

    def initialize_connections():
        fetch_configuration()

    def fetch_configuration():
        create_connection()

    def create_connection():
        conn_auth()

    def conn_auth():
        raise Exception("Can't perform the requested task - authentication error")

    start_service()
    while True:
        logging.info("service loop")
        time.sleep(10)
---
