apiVersion: v1
kind: ConfigMap
metadata:
  name: komodor-features-configuration
data:
  reportToDataLake: 'true'
  debug: 'false'
  useAPIaccelerator: 'true'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: komodor-configmap-deploy
  labels:
    app: komodor-configmap-deploy
    project: komodemo
  name: komodor-configmap-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komodor-configmap-deploy
  template:
    metadata:
      labels:
        app: komodor-configmap-deploy
    spec:
      containers:
      - env:
        image: nginx:1.23.2
        name: nginx
        volumeMounts:
          - name: komodor-features-configuration
            mountPath: /usr/share/app/config
            subPath: komodor-features-configuration
      volumes:
      - name: komodor-features-configuration
        configMap:
          name: komodor-features-configuration
