apiVersion: apps/v1
kind: Deployment
metadata:
  name: komodor-oomkilled
  labels:
    app: komodor-oomkilled
    project: komodemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komodor-oomkilled
  template:
    metadata:
      labels:
        app: komodor-oomkilled
    spec:
      containers:
      - name: komodor-oomkilled
        image: polinux/stress
        command: ["/bin/sh", "-c"]
        args: ["echo 'Going to allocate 60MB of memory!' ; echo 'Going to allocate 60MB of memory!' ; echo 'Going to allocate 60MB of memory!' ; stress --vm 2 --vm-bytes 30M --vm-hang 120 --backoff 10000000 --verbose"]
        resources:
          requests:
            memory: "40Mi"
          limits:
            memory: "40Mi"
