apiVersion: apps/v1
kind: Deployment
metadata:
  name: komodor-create-container-config-error
  labels:
    app: komodor-create-error
    project: komodemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: komodor-create-error
  template:
    metadata:
      labels:
        app: komodor-create-error
    spec:
      containers:
      - name: crash-demo
        image: nginx:1.21.6
        env: 
        - name: SECRET_TOKEN
          valueFrom:
            configMapKeyRef:
              name: api-access-tokenn
              key: SECRET_TOKEN
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-access-token
data:
  SECRET_TOKEN: dmFsdWUtMg0KDQo=
